### ISSUE TITLE
Getting build error

### ISSUE THREAD

**Issue by Vinothapplife** [jose2007kj/ionic2-login#1]
@jose2007kj  Hi jose

**Comment by jose2007kj** [comment]
i will call you in evening.......
please check by doing ionic serve...................and whats the output?
first you need to do npm install
2.add platform android(if you are trying to run on device)

**Comment by aaronksaunders** [comment]
@jose2007kj is this the same issue you are getting with the code from my repo? https://github.com/aaronksaunders/ionic2-angularfire-sample

**Comment by jose2007kj** [comment]
@aaronksaunders sir, thanks for your replay............actually i had errors(not this)  and i solved that ......but after that it  was not showing login modal....(i doubts....if it was because i logined previously  using your another app ioni2firebase3.......).............. ........now i am reffering this (https://github.com/JAVEBRATTCODE)
